version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blog_root_password
      MYSQL_DATABASE: blog_db
      MYSQL_USER: kalunge
      MYSQL_PASSWORD: blog_db_password
    ports:
      - "3306:3306"